/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;

/**
 *
 * @author lpzkn
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        toolBar1 = new javax.swing.JToolBar();
        tNew = new javax.swing.JButton();
        tOpen = new javax.swing.JButton();
        tSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        toolBar1.setBackground(new java.awt.Color(0, 0, 102));
        toolBar1.setRollover(true);

        tNew.setForeground(new java.awt.Color(255, 255, 255));
        tNew.setIcon(new javax.swing.ImageIcon("C:\\Users\\lpzkn\\Documents\\NetBeansProjects\\Practica4_U1\\Practica4_U1\\774japan_100320.png")); // NOI18N
        tNew.setText("Doramas Japoneses");
        tNew.setFocusable(false);
        tNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNewActionPerformed(evt);
            }
        });
        toolBar1.add(tNew);

        tOpen.setForeground(new java.awt.Color(255, 255, 255));
        tOpen.setIcon(new javax.swing.ImageIcon("C:\\Users\\lpzkn\\Documents\\NetBeansProjects\\Practica4_U1\\Practica4_U1\\776southkorea_100254.png")); // NOI18N
        tOpen.setText("Doramas Coreanos");
        tOpen.setFocusable(false);
        tOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tOpenActionPerformed(evt);
            }
        });
        toolBar1.add(tOpen);

        tSave.setForeground(new java.awt.Color(255, 255, 255));
        tSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\lpzkn\\Documents\\NetBeansProjects\\Practica4_U1\\Practica4_U1\\763china_100643.png")); // NOI18N
        tSave.setText("Doramas Chinos");
        tSave.setFocusable(false);
        tSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSaveActionPerformed(evt);
            }
        });
        toolBar1.add(tSave);

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lpzkn\\Documents\\NetBeansProjects\\Practica4_U1\\Practica4_U1\\domainregistrar_102158.png")); // NOI18N
        jButton3.setText("Registrarse");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        toolBar1.add(jButton3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mexico", "Estados unidos", "Brasil", "Canada", "Japon", "China", "Corea del Sur" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pais:");

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jButton1.setText("Enviar Información");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html> <body> <p align=\"center\"> <font color=\"Blue\"><b>Importante:</b> </font>Lo primero que debe de hacer es ver en toolbar, las distintas<br> opciones que aparecen, si selecciona alguna aparecera en el<br> desktop como ventanas internas, solo seran las listas.<br>  Si selecciona registro lo llevara a una ventana secundaria<br> donde se registrara, favor de ingresar los datos y dar click en registrar. <br>Una vez que dio click, los datos ingresados le apareceran en la tabla,<br> como nota, el Formatted Field esta puesto para el numero de control.<b>Por ultimo, en la ventana principal si selecciona su pais y da en enviar<b> aparecera abajo del desktop, un mensaje de gracias. </p> </body> </html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escritorio)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(toolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(toolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNewActionPerformed
        // TODO add your handling code here:
     VentanaJ ventana3 =new VentanaJ();
        Component add = escritorio.add(ventana3);
        ventana3.setVisible(true);
    }//GEN-LAST:event_tNewActionPerformed

    private void tOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tOpenActionPerformed
        // TODO add your handling code here:
        VentanaV ventana2 =new VentanaV();
        Component add = escritorio.add(ventana2);
        ventana2.setVisible(true);
    }//GEN-LAST:event_tOpenActionPerformed

    private void tSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSaveActionPerformed
        // TODO add your handling code here:
        VentanaR ventana1 =new VentanaR();
        Component add = escritorio.add(ventana1);
        ventana1.setVisible(true);
    }//GEN-LAST:event_tSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String seleccion=(String)jComboBox1.getSelectedItem();
        
if(seleccion.equals("Mexico")){
jTextArea1.append("\n Muchas gracias por tu visita mexicano ");
}

else if(seleccion.equals("Estados unidos")){
jTextArea1.append("\n Muchas gracias por tu visita Estadounidense");
}

else if(seleccion.equals("Japon")){
jTextArea1.append("\n Muchas gracias por tu visita Japones");
}

else if(seleccion.equals("Brasil")){
jTextArea1.append("\n Muchas gracias por tu visita Brasileño");
}

else if(seleccion.equals("Canada")){
jTextArea1.append("\n Muchas gracias por tu visita Canadiense");
}

else if(seleccion.equals("China")){
jTextArea1.append("\n Muchas gracias por tu visita Chino");
}

else if(seleccion.equals("Corea del Sur")){
jTextArea1.append("\n Muchas gracias por tu visita Coreano");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new RegistroT().setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton tNew;
    private javax.swing.JButton tOpen;
    private javax.swing.JButton tSave;
    private javax.swing.JToolBar toolBar1;
    // End of variables declaration//GEN-END:variables
}
